import { ProjectRepository, filterProjects, calculateStats, calculateOperationalStats, projectsToCsv, validateProject } from './domain.js';
import { getCountries, getRegions, getCities } from './locations.js';
import { createMapPickSession } from './map-pick.js';
import { PersonDirectory } from './people.js';
import { QUICK_OPTIONS, normalizeMultiValue, mergeMultiSelection, formatMultiValue } from './quick-options.js';
import { createPhotoEditor, projectPhotos, PHOTO_CATEGORIES } from './photos.js';

const TYPE_LABELS={mosque:'مسجد',school:'مدرسة قرآن',combined:'مسجد ومدرسة'};
const STATUS_LABELS={active:'يعمل',maintenance:'يحتاج صيانة',building:'قيد الإنشاء',inactive:'متوقف'};
const SAMPLE_PROJECTS=[
  {id:'demo-1',name:'مسجد النور',type:'mosque',country:'تنزانيا',region:'بيمبا',locality:'ويتي',lat:-5.055,lng:39.729,capacity:350,status:'active',manager:'عبدالله سالم',phone:'',builder:'الاستقامة',donor:'',buildDate:'2019-01-01',maintenanceNotes:'',createdBy:'المشرف العام'},
  {id:'demo-2',name:'مدرسة الفلاح للقرآن',type:'school',country:'تنزانيا',region:'بيمبا',locality:'ويتي',lat:-5.066,lng:39.714,capacity:120,status:'active',manager:'محمد علي',phone:'',builder:'الاستقامة',donor:'متبرع كريم',buildDate:'2021-01-01',maintenanceNotes:'',createdBy:'المشرف العام'},
  {id:'demo-3',name:'مسجد ومدرسة الرحمة',type:'combined',country:'تنزانيا',region:'بيمبا',locality:'مكواني',lat:-5.357,lng:39.648,capacity:280,status:'active',manager:'خالد حسن',phone:'',builder:'الاستقامة',donor:'',buildDate:'2020-01-01',maintenanceNotes:'',createdBy:'المشرف العام'},
  {id:'demo-4',name:'مسجد الهدى',type:'mosque',country:'تنزانيا',region:'زنجبار',locality:'مدينة زنجبار',lat:-6.165,lng:39.199,capacity:420,status:'maintenance',manager:'سعيد عمر',phone:'',builder:'الاستقامة',donor:'',buildDate:'2017-01-01',maintenanceNotes:'مثال تجريبي: يحتاج إلى فحص وصيانة السقف.',createdBy:'المشرف العام'},
  {id:'demo-5',name:'مدرسة البيان',type:'school',country:'تنزانيا',region:'بيمبا',locality:'مكواني',lat:-5.37,lng:39.66,capacity:85,status:'building',manager:'يوسف عبدالله',phone:'',builder:'الاستقامة',donor:'متبرع كريم',buildDate:'2023-01-01',maintenanceNotes:'',createdBy:'المشرف العام'}
];

const $=selector=>document.querySelector(selector);
const $$=selector=>[...document.querySelectorAll(selector)];
const OTHER_LOCATION='__other__';
function locationValue(selectId,customId){const value=$(`#${selectId}`).value;return value===OTHER_LOCATION?$(`#${customId}`).value.trim():value}
function populateLocationSelect(selectId,customId,values,selected,placeholder){
  const select=$(`#${selectId}`),custom=$(`#${customId}`);select.replaceChildren(new Option(placeholder,''),...values.map(value=>new Option(value,value)),new Option('أخرى — إدخال يدوي',OTHER_LOCATION));
  if(selected&&values.includes(selected)){select.value=selected;custom.hidden=true;custom.value=''}else if(selected){select.value=OTHER_LOCATION;custom.hidden=false;custom.value=selected}else{select.value='';custom.hidden=true;custom.value=''}
}
function configureLocation(country='تنزانيا',region='',locality=''){
  populateLocationSelect('country','customCountry',getCountries(),country,'اختر الدولة');
  const effectiveCountry=locationValue('country','customCountry');populateLocationSelect('region','customRegion',getRegions(effectiveCountry),region,'اختر المحافظة أو الإقليم');
  const effectiveRegion=locationValue('region','customRegion');populateLocationSelect('locality','customLocality',getCities(effectiveCountry,effectiveRegion),locality,'اختر المدينة أو القرية');
}
function updateCustomVisibility(selectId,customId){const custom=$(`#${customId}`);custom.hidden=$(`#${selectId}`).value!==OTHER_LOCATION;if(!custom.hidden)custom.focus()}
const repo=new ProjectRepository(localStorage);
repo.seed(SAMPLE_PROJECTS);
const peopleDirectory=new PersonDirectory(localStorage);
let projects=repo.list();peopleDirectory.seedFromProjects(projects);
let selectedId=null,map=null,markerLayer=null,pickingLocation=false,mapPickSession=null,mapPickMarker=null,deferredInstall=null;

function el(tag,className,text){const node=document.createElement(tag);if(className)node.className=className;if(text!==undefined)node.textContent=text;return node}
function showToast(message){const toast=$('#toast');toast.textContent=message;toast.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>toast.classList.remove('show'),2300)}
const QUICK_LABELS={daawaActivities:'النشاط الدعوي القائم',socialFeatures:'المظاهر والاهتمامات الاجتماعية',livelihoods:'الأنشطة المعيشية والتجارية',religiousIssues:'القضايا الدينية المهمة',religiousChallenges:'التحديات الدينية',socialChallenges:'التحديات الاجتماعية',proposedActivities:'الأنشطة الدعوية المقترحة'};
function renderQuickFields(){const root=$('#quickFields');root.replaceChildren();for(const [key,options] of Object.entries(QUICK_OPTIONS)){const field=document.createElement('fieldset');field.className='quick-field';field.dataset.quickField=key;const legend=document.createElement('legend');legend.textContent=QUICK_LABELS[key];const hint=el('small','quick-hint','اختر ما ينطبق');const chips=el('div','choice-chips');for(const option of options){const label=document.createElement('label'),input=document.createElement('input'),span=document.createElement('span');input.type='checkbox';input.value=option;span.textContent=option;label.append(input,span);chips.append(label)}const otherToggle=document.createElement('label');otherToggle.className='other-toggle';const toggle=document.createElement('input'),toggleText=document.createElement('span');toggle.type='checkbox';toggleText.textContent='أخرى';otherToggle.append(toggle,toggleText);chips.append(otherToggle);const other=document.createElement('input');other.type='text';other.className='quick-other';other.placeholder='اكتب إضافة قصيرة فقط';other.maxLength=240;other.hidden=true;toggle.addEventListener('change',()=>{other.hidden=!toggle.checked;if(toggle.checked)other.focus();else other.value=''});field.append(legend,hint,chips,other);root.append(field)}}
function setQuickValue(key,value){const field=document.querySelector(`[data-quick-field="${key}"]`);if(!field)return;const values=normalizeMultiValue(value),known=new Set(QUICK_OPTIONS[key]);field.querySelectorAll('.choice-chips label:not(.other-toggle) input[type="checkbox"]').forEach(input=>input.checked=values.includes(input.value));const extras=values.filter(item=>!known.has(item)),toggle=field.querySelector('.other-toggle input'),other=field.querySelector('.quick-other');toggle.checked=extras.length>0;other.hidden=!toggle.checked;other.value=extras.join('، ')}
function getQuickValue(key){const field=document.querySelector(`[data-quick-field="${key}"]`);if(!field)return[];const selected=[...field.querySelectorAll('.choice-chips label:not(.other-toggle) input:checked')].map(input=>input.value);return mergeMultiSelection(selected,field.querySelector('.quick-other').value)}
function statusClass(status){return ['maintenance','building','inactive'].includes(status)?status:''}
function download(name,content,type){const blob=new Blob([content],{type});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),500)}
function currentFilters(){return{query:$('#search').value,type:$('#typeFilter').value,region:$('#regionFilter').value,status:$('#statusFilter').value}}
function refreshRegions(){const current=$('#regionFilter').value;const regions=[...new Set(projects.map(p=>p.region).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'ar'));$('#regionFilter').replaceChildren(new Option('كل المناطق','all'),...regions.map(region=>new Option(region,region)));$('#regionFilter').value=regions.includes(current)?current:'all'}

function projectCard(project){
  const button=el('button',`project-card${project.id===selectedId?' active':''}`);button.type='button';button.dataset.id=project.id;
  const icon=el('span','project-icon',project.type==='school'?'ق':project.type==='combined'?'م+':'م');
  const body=el('span');body.append(el('h3','',project.name),el('p','',`${TYPE_LABELS[project.type]} · ${[project.locality,project.region].filter(Boolean).join('، ')}`));
  const status=el('span',`status ${statusClass(project.status)}`,STATUS_LABELS[project.status]);
  button.append(icon,body,status);button.addEventListener('click',()=>selectProject(project.id));return button;
}
function renderList(filtered){const list=$('#projectList');list.replaceChildren();if(!filtered.length)list.append(el('div','empty','لا توجد مشاريع مطابقة للفلاتر الحالية'));else filtered.forEach(project=>list.append(projectCard(project)));$('#visibleCount').textContent=filtered.length;$('#totalCount').textContent=projects.length}

function markerClass(project){return `custom-marker ${project.status==='maintenance'?'maintenance':project.type}`}
function previewMapPoint(point){if(!pickingLocation||!mapPickSession)return;const selected=mapPickSession.choose(point);if(mapPickMarker)map.removeLayer(mapPickMarker);mapPickMarker=L.circleMarker([selected.lat,selected.lng],{radius:9,color:'#d3a84c',weight:4,fillColor:'#0d5c4b',fillOpacity:1}).addTo(map);$('#mapPickText').textContent=`الموقع المختار: ${selected.lat.toFixed(6)}, ${selected.lng.toFixed(6)}`;$('#confirmMapPick').disabled=false}
function stopMapPicking(showForm=true){pickingLocation=false;$('#mapPickBar').hidden=true;if(map){map.getContainer().style.cursor='';if(mapPickMarker){map.removeLayer(mapPickMarker);mapPickMarker=null}}if(showForm){$('#modalLayer').hidden=false;document.body.style.overflow='hidden'}mapPickSession=null}
function startMapPicking(){if(!map)return showToast('الخريطة غير متاحة حاليًا');const lat=$('#lat').value.trim(),lng=$('#lng').value.trim(),original=lat&&lng?{lat:Number(lat),lng:Number(lng)}:null;mapPickSession=createMapPickSession(original);pickingLocation=true;closeDetails();switchView('map');$('#modalLayer').hidden=true;document.body.style.overflow='';$('#mapPickBar').hidden=false;$('#mapPickText').textContent='اضغط على المكان المطلوب داخل الخريطة';$('#confirmMapPick').disabled=true;map.getContainer().style.cursor='crosshair';setTimeout(()=>map.invalidateSize(),80);showToast('حدد الموقع ثم اضغط اعتماد الموقع والعودة')}
function confirmMapPicking(){if(!mapPickSession?.canConfirm())return showToast('حدد الموقع على الخريطة أولًا');const point=mapPickSession.confirm();setCoords(point.lat,point.lng);stopMapPicking(true);showToast('تم اعتماد الموقع والعودة إلى الاستمارة')}
function cancelMapPicking(){stopMapPicking(true);showToast('تم الرجوع إلى الاستمارة دون تغيير الموقع')}
function renderMarkers(filtered){if(!map||!markerLayer)return;markerLayer.clearLayers();for(const project of filtered){
  const icon=L.divIcon({className:'',html:`<div class="${markerClass(project)}"></div>`,iconSize:[34,34],iconAnchor:[17,33]});
  const marker=L.marker([project.lat,project.lng],{icon,keyboard:true,title:project.name}).addTo(markerLayer);marker.on('click',()=>pickingLocation?previewMapPoint({lat:project.lat,lng:project.lng}):selectProject(project.id));
}}
function fitFiltered(filtered){if(!map||!filtered.length)return;const bounds=L.latLngBounds(filtered.map(p=>[p.lat,p.lng]));map.fitBounds(bounds,{padding:[45,45],maxZoom:11})}
function render(){projects=repo.list();refreshRegions();const filtered=filterProjects(projects,currentFilters());renderList(filtered);renderMarkers(filtered);renderReports();$('#maintenanceBadge').textContent=projects.filter(p=>p.status==='maintenance').length}

function initMap(){
  if(!globalThis.L){$('#mapFallback').hidden=false;return}
  map=L.map('map',{zoomControl:true}).setView([-5.55,39.45],8);
  L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(map);
  markerLayer=L.layerGroup().addTo(map);
  map.on('click',event=>{if(pickingLocation)previewMapPoint(event.latlng)});
  map.on('tileerror',()=>{if(!navigator.onLine)$('#mapFallback').hidden=false});
  render();fitFiltered(projects);
}

function selectProject(id){selectedId=id;const project=repo.get(id);if(!project)return;renderList(filterProjects(projects,currentFilters()));
  $('#detailType').textContent=TYPE_LABELS[project.type];$('#detailStatus').textContent=STATUS_LABELS[project.status];$('#detailStatus').className=`status ${statusClass(project.status)}`;$('#detailName').textContent=project.name;$('#detailLocation').textContent=[project.locality,project.region,project.country].filter(Boolean).join('، ');
  const fields=[['السعة',project.capacity?`${Number(project.capacity).toLocaleString('ar-OM')} مستفيدًا`:'غير محددة'],['المسؤول',project.manager||'غير محدد'],['الهاتف',project.phone||'غير محدد'],['الجهة البانية',project.builder||'غير محددة'],['المتبرع',project.donor||'غير محدد'],['تاريخ البناء',project.buildDate||'غير محدد'],['أدخلها',project.createdBy||'غير محدد']];
  const grid=$('#detailGrid');grid.replaceChildren(...fields.map(([label,value])=>{const item=el('div','detail-item');item.append(el('small','',label),el('strong','',value));return item}));renderExtendedDetails(project);
  const note=$('#maintenanceNote');note.hidden=!project.maintenanceNotes;note.textContent=project.maintenanceNotes||'';
  const images=projectPhotos(project),image=$('#detailImage'),placeholder=$('.details-photo .placeholder');if(images.length){image.src=images[0].data;image.hidden=false;placeholder.hidden=true}else{image.hidden=true;placeholder.hidden=false}let gallery=$('#detailGallery');if(!gallery){gallery=el('div','detail-gallery');gallery.id='detailGallery';$('#detailExtended').before(gallery)}gallery.replaceChildren();for(const photo of images){const figure=document.createElement('figure'),img=document.createElement('img');img.src=photo.data;img.alt=PHOTO_CATEGORIES[photo.category]||'صورة المشروع';figure.append(img,el('figcaption','',`${img.alt}${photo.caption?' — '+photo.caption:''}`));gallery.append(figure)}
  $('#details').classList.add('open');$('#details').setAttribute('aria-hidden','false');if(map){map.flyTo([project.lat,project.lng],Math.max(map.getZoom(),11),{duration:.6})}
}
function closeDetails(){$('#details').classList.remove('open');$('#details').setAttribute('aria-hidden','true');selectedId=null;renderList(filterProjects(projects,currentFilters()))}

const ROLE_LABELS={agent:'وكيل',imam:'إمام',teacher:'معلم',administrator:'إداري',manager:'مدير',other:'أخرى'};
const OWNERSHIP_LABELS={association:'ملك الجمعية',waqf:'وقف',person:'ملك شخص',government:'حكومية',other:'أخرى'};
const yesNo=value=>value===true?'نعم':value===false?'لا':'غير محدد';
const boolValue=id=>{const value=$(`#${id}`).value;return value===''?undefined:value==='yes'};
const numberValue=id=>{const value=$(`#${id}`).value;return value===''?undefined:Number(value)};
function makeStaffField(labelText,className,type='text',value=''){
  const label=el('label','',labelText),input=document.createElement('input');input.className=className;input.type=type;input.value=value??'';if(type==='number'){input.min='0';input.step='.01'}label.append(input);return label
}
function addStaffRow(person={}){
  const row=el('div','staff-row');
  const name=makeStaffField('الاسم','staff-name','text',person.name);
  const roleLabel=el('label','','الدور'),role=document.createElement('select');role.className='staff-role';for(const [value,text] of Object.entries(ROLE_LABELS)){const option=document.createElement('option');option.value=value;option.textContent=text;option.selected=(person.role||'teacher')===value;role.append(option)}roleLabel.append(role);
  const birth=makeStaffField('تاريخ الميلاد','staff-birth','date',person.birthDate);
  const region=makeStaffField('المنطقة','staff-region','text',person.region);
  const education=makeStaffField('المستوى التعليمي','staff-education','text',person.education);
  const graduation=makeStaffField('جهة التخرج','staff-graduation','text',person.graduationInstitution);
  const salary=makeStaffField('الراتب الشهري','staff-salary','number',person.salary);
  const remove=el('button','remove-staff','×');remove.type='button';remove.title='حذف الفرد';remove.addEventListener('click',()=>{row.remove();updateStaffCount()});
  const nameInput=name.querySelector('input');nameInput.setAttribute('list','personNames');nameInput.autocomplete='off';nameInput.addEventListener('change',()=>applyPersonToStaffRow(row,nameInput.value));
  row.append(name,roleLabel,birth,region,education,graduation,salary,remove);$('#staffEditor').append(row);updateStaffCount()
}
function updateStaffCount(){$('#staffCount').textContent=$$('#staffEditor .staff-row').length.toLocaleString('ar-OM')}
function collectStaff(){return $$('#staffEditor .staff-row').map(row=>{const get=selector=>row.querySelector(selector).value.trim();return{name:get('.staff-name'),role:get('.staff-role'),birthDate:get('.staff-birth'),region:get('.staff-region'),education:get('.staff-education'),graduationInstitution:get('.staff-graduation'),salary:get('.staff-salary')===''?0:Number(get('.staff-salary'))}}).filter(person=>person.name||person.birthDate||person.region||person.education||person.graduationInstitution||person.salary)}
function refreshPersonNames(){const list=$('#personNames');list.replaceChildren(...peopleDirectory.list().sort((a,b)=>a.name.localeCompare(b.name,'ar')).map(person=>{const option=document.createElement('option');option.value=person.name;option.label=(person.roles||[]).map(role=>ROLE_LABELS[role]||role).join('، ');return option}))}
function applyPersonToStaffRow(row,name){const person=peopleDirectory.find(name);if(!person)return;const set=(selector,value)=>{if(value!==undefined&&value!==null&&value!=='')row.querySelector(selector).value=value};const preferred=(person.roles||[]).find(role=>ROLE_LABELS[role]);set('.staff-role',preferred);set('.staff-birth',person.birthDate);set('.staff-region',person.region);set('.staff-education',person.education);set('.staff-graduation',person.graduationInstitution);set('.staff-salary',person.salary);showToast('تم استرجاع بيانات الشخص المحفوظة')}
function rememberProjectPeople(project){if(project.manager)peopleDirectory.upsert({name:project.manager,role:'manager',phone:project.phone});for(const person of project.staff||[])peopleDirectory.upsert(person);refreshPersonNames()}
function setSelectBool(id,value){$(`#${id}`).value=value===true?'yes':value===false?'no':''}
function addDetailSection(container,title,lines){const valid=lines.filter(([,value])=>value!==undefined&&value!==null&&value!=='');if(!valid.length)return;const section=el('section','detail-section'),heading=el('h3','',title),body=el('div','detail-lines');for(const [label,value] of valid){const line=el('div','detail-line');line.append(el('span','',label),el('strong','',String(value)));body.append(line)}section.append(heading,body);container.append(section)}
function renderExtendedDetails(project){const box=$('#detailExtended');box.replaceChildren();const land=project.land||{},fac=project.facilities||{},community=project.community||{};
  addDetailSection(box,'الأرض والملكية', [['الملكية',OWNERSHIP_LABELS[land.ownership]||''],['المالك',land.ownerName],['المساحة',land.area!==undefined?`${Number(land.area).toLocaleString('ar-OM')} م²`:null],['الاستغلال',land.utilization!==undefined?`${land.utilization}%`:null],['قابلية التوسع',land.expandable!==undefined?yesNo(land.expandable):null]]);
  addDetailSection(box,'المرافق والاحتياجات', [['سكن المعلمين',fac.teacherHousing!==undefined?yesNo(fac.teacherHousing):null],['سكن الإمام',fac.imamHousing!==undefined?yesNo(fac.imamHousing):null],['سكن الضيوف',fac.guestHousing!==undefined?yesNo(fac.guestHousing):null],['المكتبة',fac.library!==undefined?yesNo(fac.library):null],['المصاحف',fac.quranCount],['المصاحف المطلوبة',fac.quranNeed],['القاعة',fac.hall!==undefined?yesNo(fac.hall):null],['سعة القاعة',fac.hallCapacity],['نقل الطلاب',({available:'حافلة متوفرة',needed:'توجد حاجة لحافلة',not_needed:'لا توجد حاجة'})[fac.studentTransport]],['سكن الطلاب',({nearby:'من المنطقة القريبة',mixed:'قريبون ومن مناطق بعيدة',distant:'غالبهم من مناطق بعيدة'})[fac.studentsLocal]]]);
  const staff=Array.isArray(project.staff)?project.staff:[];if(staff.length){const section=el('section','detail-section'),heading=el('h3','',`الكادر (${staff.length.toLocaleString('ar-OM')})`);section.append(heading);for(const person of staff){const card=el('div','staff-card');card.append(el('strong','',person.name),el('small','',`${ROLE_LABELS[person.role]||person.role}${person.education?` · ${person.education}`:''}${person.region?` · ${person.region}`:''}`));section.append(card)}box.append(section)}
  addDetailSection(box,'الفرع والمنطقة', [['الفرع',community.branchName],['السكان',community.population],['نسبة المسلمين',community.muslimPercentage!==undefined?`${community.muslimPercentage}%`:null],['النشاط الدعوي',formatMultiValue(community.daawaActivities)],['التحديات الدينية',formatMultiValue(community.religiousChallenges)],['التحديات الاجتماعية',formatMultiValue(community.socialChallenges)],['أنشطة مقترحة',formatMultiValue(community.proposedActivities)]]);
}

const photoEditor=createPhotoEditor({compress:compressImage,toast:showToast});
function resetForm(){
  $('#projectForm').reset();Object.keys(QUICK_OPTIONS).forEach(key=>setQuickValue(key,[]));$$('.extended-sections details,.mini-details').forEach(item=>item.open=false);$('#maintenanceField').hidden=true;$('#staffEditor').replaceChildren();updateStaffCount();configureLocation('تنزانيا','','');$('#projectId').value='';$('#builder').value='الاستقامة';$('#lat').value='';$('#lng').value='';$('#coordsText').textContent='لم يتم تحديد الموقع';photoEditor.reset();$('#formError').textContent='';$('#formTitle').textContent='إضافة مشروع';
}
function openForm(project=null){resetForm();if(project){
  $('#formTitle').textContent='تعديل المشروع';$('#projectId').value=project.id;
  for(const id of ['name','capacity','manager','phone','builder','donor','buildDate','status','maintenanceNotes'])if(project[id]!==undefined)$(`#${id}`).value=project[id];configureLocation(project.country,project.region,project.locality);
  const radio=document.querySelector(`input[name="type"][value="${project.type}"]`);if(radio)radio.checked=true;
  const land=project.land||{};const landMap={landOwnership:'ownership',landOwner:'ownerName',landArea:'area',landUtilization:'utilization',landNotes:'notes'};for(const [id,key] of Object.entries(landMap))if(land[key]!==undefined)$(`#${id}`).value=land[key];setSelectBool('landExpandable',land.expandable);
  const fac=project.facilities||{};for(const id of ['teacherHousing','imamHousing','guestHousing','library','hall'])setSelectBool(id,fac[id]);for(const id of ['quranCount','quranNeed','hallCapacity','studentTransport','studentsLocal'])if(fac[id]!==undefined)$(`#${id}`).value=fac[id];
  const community=project.community||{};for(const id of ['branchName','population','muslimPercentage','ibadiFamilies','omaniFamilies','omaniStudentPercentage','ibadiStudentPercentage','omaniTeacherPercentage','ibadiTeacherPercentage','financialCapacity'])if(community[id]!==undefined)$(`#${id}`).value=community[id];for(const key of Object.keys(QUICK_OPTIONS))setQuickValue(key,community[key]);$('#maintenanceField').hidden=project.status!=='maintenance';
  (project.staff||[]).forEach(addStaffRow);setCoords(project.lat,project.lng);photoEditor.reset(project);
}
  $('#modalLayer').hidden=false;document.body.style.overflow='hidden';setTimeout(()=>$('#name').focus(),80)
}
function closeForm(){if(photoEditor.isBusy())return;pickingLocation=false;if(map)map.getContainer().style.cursor='';$('#modalLayer').hidden=true;document.body.style.overflow=''}
function setCoords(lat,lng){$('#lat').value=Number(lat).toFixed(6);$('#lng').value=Number(lng).toFixed(6);$('#coordsText').textContent=`${Number(lat).toFixed(6)}, ${Number(lng).toFixed(6)}`}
function formProject(){const lat=$('#lat').value.trim(),lng=$('#lng').value.trim();return{
  id:$('#projectId').value||undefined,name:$('#name').value.trim(),type:$('input[name="type"]:checked').value,country:locationValue('country','customCountry'),region:locationValue('region','customRegion'),locality:locationValue('locality','customLocality'),capacity:Number($('#capacity').value||0),manager:$('#manager').value.trim(),phone:$('#phone').value.trim(),builder:$('#builder').value.trim(),donor:$('#donor').value.trim(),buildDate:$('#buildDate').value,status:$('#status').value,maintenanceNotes:$('#maintenanceNotes').value.trim(),lat:lat===''?'':Number(lat),lng:lng===''?'':Number(lng),photos:photoEditor.getPhotos(),photo:'',createdBy:'صالح الزهيمي',
  staff:collectStaff(),
  land:{ownership:$('#landOwnership').value,ownerName:$('#landOwner').value.trim(),area:numberValue('landArea'),utilization:numberValue('landUtilization'),expandable:boolValue('landExpandable'),notes:$('#landNotes').value.trim()},
  facilities:{teacherHousing:boolValue('teacherHousing'),imamHousing:boolValue('imamHousing'),guestHousing:boolValue('guestHousing'),library:boolValue('library'),quranCount:numberValue('quranCount'),quranNeed:numberValue('quranNeed'),hall:boolValue('hall'),hallCapacity:numberValue('hallCapacity'),studentTransport:$('#studentTransport').value,studentsLocal:$('#studentsLocal').value},
  community:{branchName:$('#branchName').value.trim(),population:numberValue('population'),muslimPercentage:numberValue('muslimPercentage'),ibadiFamilies:numberValue('ibadiFamilies'),omaniFamilies:numberValue('omaniFamilies'),omaniStudentPercentage:numberValue('omaniStudentPercentage'),ibadiStudentPercentage:numberValue('ibadiStudentPercentage'),omaniTeacherPercentage:numberValue('omaniTeacherPercentage'),ibadiTeacherPercentage:numberValue('ibadiTeacherPercentage'),financialCapacity:$('#financialCapacity').value,daawaActivities:getQuickValue('daawaActivities'),socialFeatures:getQuickValue('socialFeatures'),livelihoods:getQuickValue('livelihoods'),religiousIssues:getQuickValue('religiousIssues'),religiousChallenges:getQuickValue('religiousChallenges'),socialChallenges:getQuickValue('socialChallenges'),proposedActivities:getQuickValue('proposedActivities')}
}}
function compressImage(file,maxSize=1200,quality=.78){return new Promise((resolve,reject)=>{if(!file.type.startsWith('image/'))return reject(new Error('الملف المختار ليس صورة'));const reader=new FileReader();reader.onerror=()=>reject(new Error('تعذر قراءة الصورة'));reader.onload=()=>{const image=new Image();image.onerror=()=>reject(new Error('تعذر فتح الصورة'));image.onload=()=>{const scale=Math.min(1,maxSize/Math.max(image.width,image.height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(image.width*scale));canvas.height=Math.max(1,Math.round(image.height*scale));canvas.getContext('2d').drawImage(image,0,0,canvas.width,canvas.height);resolve(canvas.toDataURL('image/jpeg',quality))};image.src=reader.result};reader.readAsDataURL(file)})}

function renderReports(){const stats=calculateStats(projects);$('#statTotal').textContent=stats.total.toLocaleString('ar-OM');$('#statCapacity').textContent=stats.capacity.toLocaleString('ar-OM');$('#statMaintenance').textContent=stats.maintenance.toLocaleString('ar-OM');const regions=[...new Set(projects.map(p=>p.region).filter(Boolean))];$('#statRegions').textContent=regions.length.toLocaleString('ar-OM');const ops=calculateOperationalStats(projects);$('#opStaff').textContent=ops.staff.toLocaleString('ar-OM');$('#opPayroll').textContent=ops.monthlyPayroll.toLocaleString('ar-OM');$('#opExpandable').textContent=ops.expandableSites.toLocaleString('ar-OM');$('#opQuranNeed').textContent=ops.quranNeed.toLocaleString('ar-OM');$('#opHousing').textContent=ops.housingGaps.toLocaleString('ar-OM');$('#opTransport').textContent=ops.transportNeeds.toLocaleString('ar-OM');
  const bars=$('#typeBars');bars.replaceChildren();const max=Math.max(1,...Object.values(stats.types));for(const type of ['mosque','school','combined']){const row=el('div','bar-row');row.append(el('span','',TYPE_LABELS[type]));const track=el('div','bar-track'),fill=el('div','bar-fill');fill.style.width=`${stats.types[type]/max*100}%`;track.append(fill);row.append(track,el('strong','',stats.types[type].toLocaleString('ar-OM')));bars.append(row)}
  const counts=new Map();projects.forEach(p=>counts.set(p.region||'غير محدد',(counts.get(p.region||'غير محدد')||0)+1));const table=$('#regionTable');table.replaceChildren(...[...counts.entries()].sort((a,b)=>b[1]-a[1]).map(([region,count])=>{const row=el('div','region-row');row.append(el('span','',region),el('strong','',count.toLocaleString('ar-OM')));return row}))}
function switchView(view){$$('[data-view]').forEach(button=>button.classList.toggle('active',button.dataset.view===view));$('#reportView').hidden=view!=='reports';$('#mapView').hidden=view==='reports';$('#filtersBar').hidden=view==='reports';$('#mapView').classList.toggle('list-mode',view==='projects');if(view==='maintenance'){$('#statusFilter').value='maintenance';render()}else if(view==='map'||view==='projects'){$('#statusFilter').value='all';render()}const titles={map:['الخارطة الرقمية للمشاريع','المساجد ومدارس القرآن في شاشة واحدة'],projects:['سجل المشاريع','عرض وتصفية جميع المشاريع'],maintenance:['احتياجات الصيانة','المشاريع التي تتطلب المتابعة'],reports:['التقارير والإحصاءات','مؤشرات موجزة لدعم القرار']};$('#viewTitle').textContent=titles[view][0];$('#viewSubtitle').textContent=titles[view][1];if(map&&view!=='reports')setTimeout(()=>map.invalidateSize(),80)}

$('#country').addEventListener('change',()=>{updateCustomVisibility('country','customCountry');const country=locationValue('country','customCountry');populateLocationSelect('region','customRegion',getRegions(country),'','اختر المحافظة أو الإقليم');populateLocationSelect('locality','customLocality',[],'','اختر المدينة أو القرية')});
$('#region').addEventListener('change',()=>{updateCustomVisibility('region','customRegion');const country=locationValue('country','customCountry'),region=locationValue('region','customRegion');populateLocationSelect('locality','customLocality',getCities(country,region),'','اختر المدينة أو القرية')});
$('#locality').addEventListener('change',()=>updateCustomVisibility('locality','customLocality'));
$('#status').addEventListener('change',()=>{$('#maintenanceField').hidden=$('#status').value!=='maintenance';if($('#maintenanceField').hidden)$('#maintenanceNotes').value=''});
$('#addBtn').addEventListener('click',()=>openForm());$('#mobileAdd').addEventListener('click',()=>openForm());$('#addStaff').addEventListener('click',()=>addStaffRow());$('#closeModal').addEventListener('click',closeForm);$('#cancelForm').addEventListener('click',closeForm);

$('#manager').addEventListener('change',()=>{const person=peopleDirectory.find($('#manager').value);if(person?.phone&&!$('#phone').value)$('#phone').value=person.phone;if(person)showToast('تم اختيار شخص محفوظ من دليل الأسماء')});
$('#gpsBtn').addEventListener('click',()=>{if(!navigator.geolocation)return showToast('الموقع الجغرافي غير مدعوم على هذا الجهاز');$('#gpsBtn').textContent='جارٍ تحديد الموقع...';navigator.geolocation.getCurrentPosition(position=>{setCoords(position.coords.latitude,position.coords.longitude);$('#gpsBtn').textContent='التقاط موقعي';showToast('تم التقاط الموقع بنجاح')},()=>{$('#gpsBtn').textContent='التقاط موقعي';showToast('تعذر الوصول للموقع؛ اختره على الخريطة')},{enableHighAccuracy:true,timeout:10000})});
$('#mapPickBtn').addEventListener('click',startMapPicking);$('#confirmMapPick').addEventListener('click',confirmMapPicking);$('#cancelMapPick').addEventListener('click',cancelMapPicking);

$('#projectForm').addEventListener('submit',event=>{event.preventDefault();if(photoEditor.isBusy())return;if(photoEditor.hasUnaccepted()){showToast('اعتمد الصورة الملتقطة أو ألغها قبل حفظ المشروع');return}const project=formProject();const result=validateProject(project);if(!project.country)result.errors.country='الدولة مطلوبة';if(!project.region)result.errors.region='المنطقة مطلوبة';if(Object.keys(result.errors).length){$('#formError').textContent=Object.values(result.errors)[0];return}try{if(project.id)repo.update(project.id,project);else repo.create(project);rememberProjectPeople(project);closeForm();render();showToast(project.id?'تم تحديث المشروع':'تم حفظ المشروع محليًا');if(map)fitFiltered(filterProjects(projects,currentFilters()))}catch(error){$('#formError').textContent=error.name==='QuotaExceededError'?'مساحة التخزين ممتلئة؛ احذف صورًا أو صدّر نسخة احتياطية':error.message}});
$('#closeDetails').addEventListener('click',closeDetails);$('#editBtn').addEventListener('click',()=>{const project=repo.get(selectedId);if(project)openForm(project)});$('#directionsBtn').addEventListener('click',()=>{const p=repo.get(selectedId);if(p)window.open(`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(`${p.lat},${p.lng}`)}`,'_blank','noopener')});$('#deleteBtn').addEventListener('click',()=>{$('#confirmLayer').hidden=false});$('#cancelDelete').addEventListener('click',()=>{$('#confirmLayer').hidden=true});$('#confirmDelete').addEventListener('click',()=>{if(selectedId)repo.remove(selectedId);$('#confirmLayer').hidden=true;closeDetails();render();showToast('تم حذف المشروع')});
['search','typeFilter','regionFilter','statusFilter'].forEach(id=>$(`#${id}`).addEventListener(id==='search'?'input':'change',render));$('#resetFilters').addEventListener('click',()=>{$('#search').value='';$('#typeFilter').value='all';$('#regionFilter').value='all';$('#statusFilter').value='all';render();fitFiltered(projects)});$$('[data-view]').forEach(button=>button.addEventListener('click',()=>switchView(button.dataset.view)));
$('#locateBtn').addEventListener('click',()=>{if(!navigator.geolocation)return showToast('خدمة الموقع غير مدعومة');navigator.geolocation.getCurrentPosition(position=>{if(map){map.flyTo([position.coords.latitude,position.coords.longitude],14);L.circleMarker([position.coords.latitude,position.coords.longitude],{radius:7,color:'#0d5c4b',fillColor:'#fff',fillOpacity:1,weight:4}).addTo(map)}},()=>showToast('تعذر الوصول إلى موقعك'),{enableHighAccuracy:true,timeout:10000})});
$('#exportCsv').addEventListener('click',()=>{download(`istiqama-projects-${new Date().toISOString().slice(0,10)}.csv`,projectsToCsv(projects),'text/csv;charset=utf-8');showToast('تم تصدير ملف CSV')});$('#exportJson').addEventListener('click',()=>download(`istiqama-backup-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify(projects,null,2),'application/json'));
$('#importJson').addEventListener('change',async event=>{const file=event.target.files[0];if(!file)return;try{const data=JSON.parse(await file.text());repo.replaceAll(data);projects=repo.list();peopleDirectory.seedFromProjects(projects);refreshPersonNames();render();fitFiltered(projects);showToast('تم استيراد النسخة الاحتياطية')}catch(error){showToast(error.message||'تعذر استيراد الملف')}finally{event.target.value=''}});
window.addEventListener('online',()=>{$('#offlineBanner').hidden=true;$('#mapFallback').hidden=true;showToast('عاد الاتصال بالإنترنت')});window.addEventListener('offline',()=>{$('#offlineBanner').hidden=false});$('#offlineBanner').hidden=navigator.onLine;
window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();deferredInstall=event;$('#installBtn').hidden=false});$('#installBtn').addEventListener('click',async()=>{if(!deferredInstall)return;deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null;$('#installBtn').hidden=true});window.addEventListener('appinstalled',()=>showToast('تم تثبيت التطبيق'));
document.addEventListener('keydown',event=>{if(event.key==='Escape'){if(photoEditor.blocksClose()){event.preventDefault();return}if(pickingLocation)cancelMapPicking();else{closeForm();closeDetails();$('#confirmLayer').hidden=true}}});
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
renderQuickFields();refreshPersonNames();refreshRegions();renderReports();initMap();
