export const PHOTO_CATEGORIES={unspecified:'غير محدد',mosque_front:'واجهة المسجد',mosque_inside:'داخل المسجد',school_front:'واجهة المدرسة',school_inside:'داخل المدرسة / الفصول',land:'الأرض والساحات',facilities:'المرافق والخدمات',maintenance:'موضع يحتاج صيانة',other:'أخرى'};
export function projectPhotos(project){return Array.isArray(project.photos)?structuredClone(project.photos):project.photo?[{id:'legacy-photo',data:project.photo,category:'unspecified',caption:''}]:[]}
export function createPhotoEditor({compress,toast}){
  const $=s=>document.querySelector(s);let photos=[],candidate=null,replacement=null,busy=false,picker=false,generation=0;
  function render(){const root=$('#photoGallery');root.replaceChildren();$('#photoCount').textContent=`${photos.length} صور`;for(const photo of photos){const card=document.createElement('article');card.className='photo-card';const image=document.createElement('img');image.src=photo.data;image.alt=PHOTO_CATEGORIES[photo.category]||'صورة المشروع';const label=document.createElement('label');label.textContent='نوع الصورة';const select=document.createElement('select');select.className='photo-category';select.setAttribute('aria-label','نوع الصورة');for(const [key,text]of Object.entries(PHOTO_CATEGORIES))select.append(new Option(text,key));select.value=photo.category||'unspecified';const caption=document.createElement('input');caption.className='photo-caption';caption.placeholder='وصف مختصر (اختياري)';caption.maxLength=160;caption.value=photo.caption||'';caption.hidden=select.value!=='other';select.onchange=()=>{photo.category=select.value;image.alt=PHOTO_CATEGORIES[photo.category];caption.hidden=select.value!=='other'};caption.oninput=()=>photo.caption=caption.value;label.append(select);const actions=document.createElement('div');actions.className='photo-actions';for(const [text,cls,callback]of [['إعادة التقاط','photo-retake',()=>{replacement=photo.id;openPicker('#cameraPhoto')}],['حذف','photo-remove',()=>{photos=photos.filter(p=>p.id!==photo.id);render()}]]){const button=document.createElement('button');button.type='button';button.className=`secondary ${cls}`;button.textContent=text;button.onclick=callback;actions.append(button)}card.append(image,label,caption,actions);root.append(card)}}
  function clearCandidate(){candidate=null;replacement=null;$('#captureReview').hidden=true;$('#capturePreview').removeAttribute('src')}
  function openPicker(selector){picker=true;$(selector).value='';$(selector).click()}
  function setBusy(value){busy=value;$('#saveBtn').disabled=value;$('#choosePhotos').disabled=value;$('#takePhoto').disabled=value}
  function reset(project={}){generation++;picker=false;setBusy(false);photos=projectPhotos(project);clearCandidate();$('#photoProgress').textContent='';render()}
  $('#choosePhotos').onclick=()=>openPicker('#photo');$('#takePhoto').onclick=()=>{clearCandidate();openPicker('#cameraPhoto')};
  for(const selector of ['#photo','#cameraPhoto']){const input=$(selector);input.addEventListener('click',()=>picker=true);input.addEventListener('cancel',()=>{setTimeout(()=>picker=false,250);$('#photoProgress').textContent='تم إلغاء الاختيار؛ بيانات الاستمارة محفوظة'});input.addEventListener('change',async()=>{const files=[...input.files];if(!files.length){picker=false;return}const token=generation;setBusy(true);try{let successes=0;for(const file of files){try{$('#photoProgress').textContent=`تجهيز الصورة ${successes+1} من ${files.length}`;if(file.size>25*1024*1024)throw new Error('الصورة أكبر من 25 MB');const data=await compress(file,1000,.72);if(token!==generation)return;const photo={id:crypto.randomUUID(),data,category:'unspecified',caption:'',source:selector==='#cameraPhoto'?'camera':'device'};if(selector==='#cameraPhoto'){candidate=photo;$('#capturePreview').src=data;$('#captureReview').hidden=false}else{photos.push(photo);render()}successes++}catch(error){toast(error.message)}}$('#photoProgress').textContent=selector==='#cameraPhoto'?'راجع الصورة ثم اعتمدها أو أعد التقاطها':`تمت إضافة ${successes} صور إلى الاستمارة`}finally{input.value='';if(token===generation){setBusy(false);setTimeout(()=>picker=false,250)}}})}
  $('#acceptCapture').onclick=()=>{if(!candidate)return;const index=photos.findIndex(p=>p.id===replacement);if(index>=0)photos[index]={...photos[index],data:candidate.data,source:'camera'};else photos.push(candidate);clearCandidate();render();$('#photoProgress').textContent='أضيفت الصورة إلى الاستمارة؛ احفظ المشروع لإتمام الحفظ';toast('أضيفت الصورة؛ اضغط حفظ المشروع لحفظها نهائيًا')};$('#retakeCapture').onclick=()=>openPicker('#cameraPhoto');$('#cancelCapture').onclick=clearCandidate;
  return{reset,getPhotos:()=>structuredClone(photos),blocksClose:()=>picker||busy,hasUnaccepted:()=>Boolean(candidate),isBusy:()=>busy};
}
