/**
 * UUID version 7 (RFC 9562 §5.7): 48-bit Unix milliseconds, 4-bit version, 12-bit counter
 * (`rand_a`, used as the "fixed-length dedicated counter" of §6.2 method 1), 2-bit variant and
 * 62 random bits.
 *
 * Ids generated by one device are strictly increasing, also inside one millisecond and when
 * the wall clock steps backwards: the counter is seeded randomly (11 bits, so there is always
 * head room) on every new millisecond and incremented otherwise; when it overflows the
 * timestamp is advanced by one millisecond instead of waiting.
 */

const HEX: string[] = [];
for (let i = 0; i < 256; i++) HEX.push((i + 0x100).toString(16).slice(1));

let lastMs = -1;
let counter = 0;

function fillRandom(bytes: Uint8Array<ArrayBuffer>): void {
  const c = (globalThis as { crypto?: Crypto }).crypto;
  if (c && typeof c.getRandomValues === 'function') {
    c.getRandomValues(bytes);
    return;
  }
  // Very old WebViews only. Ids stay unique enough for row keys (timestamp + counter),
  // they are never used as secrets.
  for (let i = 0; i < bytes.length; i++) bytes[i] = Math.floor(Math.random() * 256);
}

/** Builds the canonical text form from a timestamp, a 12-bit counter and 8 random bytes. */
function format(ms: number, seq: number, rand: Uint8Array): string {
  const hi = Math.floor(ms / 0x100000000); // upper 16 bits of the 48-bit timestamp
  const lo = ms >>> 0; // lower 32 bits
  const b6 = 0x70 | ((seq >>> 8) & 0x0f); // version 7 + counter high nibble
  const b7 = seq & 0xff;
  const b8 = 0x80 | ((rand[0] ?? 0) & 0x3f); // variant 10xx
  return (
    HEX[(hi >>> 8) & 0xff]! +
    HEX[hi & 0xff]! +
    HEX[(lo >>> 24) & 0xff]! +
    HEX[(lo >>> 16) & 0xff]! +
    '-' +
    HEX[(lo >>> 8) & 0xff]! +
    HEX[lo & 0xff]! +
    '-' +
    HEX[b6]! +
    HEX[b7]! +
    '-' +
    HEX[b8]! +
    HEX[rand[1] ?? 0]! +
    '-' +
    HEX[rand[2] ?? 0]! +
    HEX[rand[3] ?? 0]! +
    HEX[rand[4] ?? 0]! +
    HEX[rand[5] ?? 0]! +
    HEX[rand[6] ?? 0]! +
    HEX[rand[7] ?? 0]!
  );
}

/**
 * Returns a new UUIDv7 in canonical lower-case text form.
 * @param now  clock override for tests (milliseconds since the Unix epoch)
 */
export function uuidv7(now: number = Date.now()): string {
  const rand = new Uint8Array(10);
  fillRandom(rand);

  let ms = Math.floor(now);
  if (!Number.isFinite(ms) || ms < 0) ms = 0;

  if (ms > lastMs) {
    lastMs = ms;
    // 11 random bits: the most significant counter bit starts at 0 (RFC 9562 §6.2 guidance).
    counter = (((rand[8] ?? 0) << 8) | (rand[9] ?? 0)) & 0x7ff;
  } else {
    // Same millisecond, or the clock went backwards: keep counting on the last timestamp.
    counter += 1;
    if (counter > 0xfff) {
      lastMs += 1;
      counter = (((rand[8] ?? 0) << 8) | (rand[9] ?? 0)) & 0x7ff;
    }
  }
  return format(lastMs, counter, rand);
}

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

/** True for any RFC 9562 text UUID (any version). */
export function isUuid(value: unknown): value is string {
  return typeof value === 'string' && UUID_RE.test(value);
}

/** Milliseconds since the Unix epoch encoded in a UUIDv7, or `null` for other versions. */
export function uuidv7Timestamp(id: string): number | null {
  if (!isUuid(id) || id[14] !== '7') return null;
  return parseInt(id.slice(0, 8) + id.slice(9, 13), 16);
}

/** Test hook: forget the monotonic state. */
export function __resetUuidv7ForTests(): void {
  lastMs = -1;
  counter = 0;
}
